### ISSUE TITLE
What is the input?

### ISSUE THREAD

**Issue by xusharon** [alexandru-dinu/bayes-net#1]
I think your code is  interesting and I want to practice it, but I don't understand the contents of your four input files. Can you tell me what these four inputs mean? I would be very grateful if you reply to me，thank you！

**Comment by alexandru-dinu** [comment]
Hello,

Thank you for your interest! I have updated the [README](https://github.com/alexandru-dinu/bayes-net/blob/master/README.md) file with info about input format.
